# Generated by Django 3.0.4 on 2020-04-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratchy', '0003_auto_20200331_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
